products = [
     'Angelica', 'Anise', 'Arugula', 'Apple', 'Apricot', 'Asparagus', 'Aubergine', 'Banana', 'Basil', 'Beef',
     'Beetroot', 'Blackberry', 'Blackcurrants', 'Bramley apple', 'Broad bean', 'Broccoli', 'Brussels sprouts',
     'Cabbage', 'Caraway', 'Cardamom', 'Carrot', 'Cauliflower', 'Cavolo nero', 'Celeriac', 'Celery', 'Cherry',
     'Chervil', 'Chestnut', 'Chicken', 'Chicory', 'Clementine', 'Cloves', 'Cod', 'Coriander', 'Courgette',
     'Courgette flower', 'Crab', 'Cranberry', 'Cranberries', 'Cumin', 'Damson', 'Date', 'Dates', 'Dill', 'Duck',
     'Fennel bulb', 'Fenugreek', 'Fig', 'Garlic', 'Globe artichoke', 'Goose', 'Gooseberry', 'Gooseberries',
     'Grapefruit', 'Grouse', 'Guinea fowl', 'Halibut', 'Jerusalem artichoke', 'Kale', 'Kipper', 'Kohlrabi', 'Lamb',
     "Lamb's lettuce", 'Lavender', 'Leek', 'Lemon', 'Lemongrass', 'Lettuce', 'Mackerel', 'Marjoram', 'Marrow', 'Mint',
     'Mussels', 'Nectarine', 'New potatoes', 'Onion', 'Orange', 'Oregano', 'Oyster', 'Pak choi', 'Parsnip', 'Peach',
     'Pear', 'Peas', 'Pepper', 'Plum', 'Pomegranate', 'Pork', 'Potato', 'Pumpkin', 'Purple sprouting', 'Quince',
     'Radicchio', 'Radish', 'Raspberry', 'Redcurrant', 'Rhubarb', 'Rocket', 'Runner bean', 'Sage', 'Salmon', 'Salsify',
     'Samphire', 'Sorrel', 'Spinach', 'Spring greens', 'Spring lamb', 'Spring onion', 'Strawberry', 'Swede',
     'Sweet potato', 'Sweetcorn', 'Swiss chard', 'Tarragon', 'Thyme', 'Tomato', 'Tuna', 'Turkey', 'Turnip', 'Venison',
     'Watercress', 'Watermelon', 'Whiting',
]
