# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='recipe',
        ),
        migrations.AddField(
            model_name='product',
            name='recipe',
            field=models.ManyToManyField(to='api.Recipe'),
        ),
    ]
