# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-08 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='source',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
