# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170421_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available_from',
        ),
        migrations.RemoveField(
            model_name='product',
            name='available_to',
        ),
        migrations.AddField(
            model_name='product',
            name='apr',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='aug',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='dec',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='feb',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='jan',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='jul',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='jun',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='mar',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='may',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='nov',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='oct',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='sep',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
