# Generated by Django 2.1.2 on 2018-11-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20181108_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='slug',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
