# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170421_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='additional',
            field=models.CharField(default=b'[]', max_length=200),
        ),
    ]
