# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-06 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_recipe_additional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='additional',
            field=models.CharField(default='[]', max_length=200),
        ),
    ]
