# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-07 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_recipe_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='additional',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
